version: '3'

tasks:
  # run
  run:
    dotenv: ['.env']
    cmds:
      - pnpm dev

  # buiild
  build:
    cmds:
      - docker build -t namhq1989/bapbi-ldp:latest -t namhq1989/bapbi-ldp:$(git rev-parse --short HEAD) .
      - docker push namhq1989/bapbi-ldp:latest
      - docker push namhq1989/bapbi-ldp:$(git rev-parse --short HEAD)