version: '3'

tasks:
  # run
  run:
    dotenv: ['.env']
    cmds:
      - pnpm dev

  # buiild
  build:
    cmds:
      - docker build -t namhq1989/tapnchill-landing-page:latest -t namhq1989/tapnchill-landing-page:$(git rev-parse --short HEAD) .
      - docker push namhq1989/tapnchill-landing-page:latest
      - docker push namhq1989/tapnchill-landing-page:$(git rev-parse --short HEAD)